services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  worker:
    build:
      context: ./backend/worker
      dockerfile: Dockerfile
    depends_on:
      - backend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    